#!/usr/bin/env bash
# This script prints "To infinity and beyond" indefinitely and survives SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
  echo "To infinity and beyond"
  sleep 2
done

